### ISSUE TITLE
AsyncLocalScopeManager uses static for an instance variable

### ISSUE THREAD

**Issue by ndrwrbgs** [opentracing/opentracing-csharp#93]
```
private static AsyncLocal<IScope> s_current = new AsyncLocal<IScope>();
```

If the user is using 2 tracers at the same time, both using an instance of AsyncLocalScopeManager underlying, then there is only 1 `s_current` shared between both of these tracers. I believe this was meant to be a private readonly variable rather than static.

It's minor, but conceivable that composite tracers may hit this problem.

**Comment by cwe1ss** [comment]
I based this code on https://github.com/aspnet/HttpAbstractions/blob/622d112372ed11075af160b1fb5a11a7637ff516/src/Microsoft.AspNetCore.Http/HttpContextAccessor.cs which also uses `static`. They did this because of https://github.com/aspnet/HttpAbstractions/issues/723 (different behavior for net45 vs netstandard) so I think we should keep this.

I *think* that there should never be more than one `IScopeManager` in use. Even if you use multiple tracers with a composite tracer, you would only ever use its scope manager and never access the scope manager of the underlying tracer instances because the composite tracer would store a `CompositeSpan` (which contains the spans of each underlying tracer).

**Comment by cwe1ss** [comment]
> @ndrwrbgs Therefore should this AsyncLocalScopeManager class not also be static?

It can't be because it couldn't implement the interface in that case.

> @ndrwrbgs We have no such existing issues, so we aren’t mandated in the same way to preserve weird behavior :)

Unfortunately, we do because the `net45` variant [is a static call](https://github.com/opentracing/opentracing-csharp/blob/2839751975905e9a10dcef5f48bbec53093b4ea1/src/OpenTracing/Util/AsyncLocalScopeManager.cs#L30) as well. Changing the behavior for `netstandard` would mean that the class has different behavior depending on which target framework a user chooses, so it's exactly the same issue.

> @ndrwrbgs As I implement a tracer then I have a concern, when I am forced to return
my ScopeManager, then I cannot new up an instance of this Async one, right?

You could give people an option to pass an existing `IScopeManager` to your tracer. That's how it's currently done in [jaeger-client-csharp](https://github.com/jaegertracing/jaeger-client-csharp/blob/master/src/Jaeger.Core/Tracer.cs#L187). We only [create our own IScopeManager](https://github.com/jaegertracing/jaeger-client-csharp/blob/d4ae3b432f86c66e0f8a2c8e9dcee0644ca7a86f/src/Jaeger.Core/Tracer.cs#L256) if the user didn't supply one.

All of that is not 100% ideal but I guess there's not much we can do as long as we support `net45`. (At least I don't know of any other solution)

**Comment by ndrwrbgs** [comment]
> It can't be because it couldn't implement the interface in that case.

I completely agree. Apologies I was ambiguous in my intent. My intent was if A -> B, and !B, then we know !A. So if from what we've seen the AsyncLocalScopeManager class should be static (because separate instances of it actually talk to the same data), but it cannot be static, then separate instances of it should not talk to the same data, right?

> Unfortunately, we do because the net45 variant is a static call as well.

Looks here like a bug in the implementation by using only the AppDomain's ID - when I implemented the similar class in the EventHook tracer you'll see that I also used a GUID, so that each instance can indeed be an instance. It sounds like we should update the `AsyncLocalScopeManager` to do the same since it's an instance class and a static. Any reason this won't work? I propose this as the solution to _"All of that is not 100% ideal but I guess there's not much we can do"_

**Comment by cwe1ss** [comment]
> Any reason this won't work? 

No, this sounds like a possible solution. I don't know what AsyncLocal does under the hood (IDK the difference between CallContext, ExecutionContext, ...) so I don't know if whatever AsyncLocal does is really instance specific. If you want to create a PR for this, it would be great to also create some unit tests that prove the correct behavior. 

I still don't think that there should ever be multiple scope manager instances though.

**Comment by ndrwrbgs** [comment]
> I still don't think that there should ever be multiple scope manager instances though.

I agree, but unless it's impossible to do someone somewhere will do it and spend weeks debugging the errors :smile:

I'll work on tests and a change for it!
